##### ALACRITTY CONFIG ##### 
# to show hints for hyperlinks= alt-u 

[window]
  startup_mode = "Maximized"
  decorations =  "None" 
  opacity = 0.99
  blur = true
  padding.x = 0
  padding.y = 0

[font]
  size = 12
  normal = { family = "Victor Mono Nerd Font", style = "Regular"}
  italic = { family = "Victor Mono Nerd Font", style = "Italic"}
  bold = { family = "Victor Mono Nerd Font", style = "Bold"}

[terminal.shell]
  program = "/usr/local/bin/tmux"
  args = ["-u", "new-session", "-A", "-D", "-s", "x"]

[selection]
  semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard = true

[keyboard]
  bindings = [
     { key="V", mods="Control|Shift", action="Paste" },
     { key="C", mods="Control|Shift", action="Copy" },
  ]

[[hints.enabled]]
  command = "xdg-open" # On Linux/BSD
  hyperlinks = true
  post_processing = true
  persist = false
  mouse.enabled = true
  binding = { key = "U", mods = "Alt" }
  regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[general]
import = [
  # "~/.config/alacritty/themes/themes/tokyo_night.toml",
  "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml",
  # "~/.config/alacritty/tokyonight.toml",
]

